/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "drei/useGLTF";
import {useSpring, a} from "@react-spring/three";

export default function Model({position}) {

  const clickExpand = () => {
    setExpand(!expand);
  }

  const [expand, setExpand] = useState(false);

  const springStuff = useSpring({
    scale: expand ? [1.4, 1.4, 1.4] : [1, 1, 1],
  });

  const group = useRef();
  const { nodes, materials } = useGLTF("/Flower.gltf");
  return (
    <a.group ref={group} dispose={null} onClick = {clickExpand} position={position} scale={springStuff.scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Stem}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials.Petals}
      />
    </a.group>
  );
}

useGLTF.preload("/Flower.gltf");